version: '3.4'

services:
  airpool:
    image: airpool
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
      DOMAIN: https://airpool.swarthmore.edu/
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    ports:
      - "${INTERNAL_PORT}:3000"
    command: sh -c "sleep 10 && npx prisma db push && npm start "

  db:
    image: mariadb:10.7
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env