import './globals.css'

import { Raleway } from 'next/font/google'

const raleway = Raleway({
  subsets: ['latin'],
  weight: '400', // TODO: Switch to variable font sizing b/c I just copied this from RSDv2
  variable: '--font-base',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={raleway.variable}>
      <body className="leading bg-page-bg">{children}</body>
    </html>
  )
}
